#[[main]]
#  identifier = "about"
#  name = "어바웃"
#  url = "about"
#  weight = 1

[[main]]
  identifier = "posts"
  name = "포스트"
  url = "posts"
  weight = 2

[[main]]
  identifier = "showcase"
  name = "쇼케이스"
  url = "showcase"
  weight = 3