#[[main]]
#  identifier = "about"
#  name = "à-propos"
#  url = "about"
#  weight = 1

[[main]]
  identifier = "posts"
  name = "articles"
  url = "posts"
  weight = 2

[[main]]
  identifier = "showcase"
  name = "showcase"
  url = "showcase"
  weight = 3